development:
  adapter: postgresql
  database: db/jsl_online_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/jsl_online_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/jsl_online_production
  pool: 5
  timeout: 5000
